before_install:
- openssl aes-256-cbc -K $encrypted_22a80512e0f7_key -iv $encrypted_22a80512e0f7_iv
  -in sdg-staging-deploy-key.enc -out ~\/.ssh/sdg-staging-deploy-key -d

matrix:
  include:
  - name: Core
    language: python
    sudo: required
    dist: bionic
    python: '3.7'
    cache:
      pip: true
      directories:
      - core/app/static/.webassets-cache
    install:
    - bash core/install.sh
    script:
    - bash core/test.sh
  - name: Planner
    language: node_js
    dist: xenial
    node_js: '10'
    addons:
      chrome: stable
    cache: npm
    install:
    - bash planner/install.sh
    script:
    - bash planner/test.sh
deploy:
  provider: script
  script: ".scripts/deploy.sh"
  on:
    branch: master
