dist: focal
os: linux
language: python
python: '3.8'

jobs:
  include:
  - name: Core
    language: python
    dist: focal
    python: '3.8'
    services:
    - docker
    cache:
      pip: true
      directories:
      - core/app/static/.webassets-cache
    install:
    - bash core/install.sh
    script:
    - bash core/start.sh coverage
  # - name: Planner
  #   language: node_js
  #   dist: xenial
  #   node_js: '10'
  #   addons:
  #     chrome: stable
  #   cache: npm
  #   install:
  #   - bash planner/install.sh
  #   script:
  #   - bash planner/test.sh
