language: python

python:
- '3.5'

sudo: required

services:
  - docker

cache:
  pip: true
  directories:
    - core/app/static/.webassets-cache

before_install:
- openssl aes-256-cbc -K $encrypted_c06b03728789_key -iv $encrypted_c06b03728789_iv
  -in veleda-deploy-key.enc -out veleda-deploy-key -d

install:
- bash .scripts/install.sh

script:
- grep -q INTEGRATION_TESTS=True core/secrets.core
- ./start.sh
- docker exec core python manage.py test

after_success:
- bash .scripts/deploy.sh
