language: python
sudo: required
dist: xenial
python: "3.7"

cache:
  pip: true
  directories:
    - core/app/static/.webassets-cache

before_install:
- openssl aes-256-cbc -K $encrypted_22a80512e0f7_key -iv $encrypted_22a80512e0f7_iv
  -in flowleaf-deploy-key.enc -out flowleaf-deploy-key -d

install:
- bash .scripts/install.sh

script:
- bash .scripts/test.sh

after_success:
- bash .scripts/deploy.sh
