language: python

python:
- '3.6'

cache:
  pip: true
  directories:
    - core/app/static/.webassets-cache

before_install:
- openssl aes-256-cbc -K $encrypted_c06b03728789_key -iv $encrypted_c06b03728789_iv
  -in veleda-deploy-key.enc -out veleda-deploy-key -d

install:
- bash .scripts/install.sh

script:
- export FLASK_CONFIG=testing
- python -u core/manage.py test

after_success:
- bash .scripts/deploy.sh
