matrix:
  include:
  - name: Core
    language: python
    sudo: required
    dist: focal
    python: '3.8'
    cache:
      pip: true
      directories:
      - core/app/static/.webassets-cache
    install:
    - bash core/install.sh
    script:
    - bash core/test.sh
  - name: Planner
    language: node_js
    dist: xenial
    node_js: '10'
    addons:
      chrome: stable
    cache: npm
    install:
    - bash planner/install.sh
    script:
    - bash planner/test.sh
