version: "3"
services:
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    depends_on:
#      - web
  web:
    build: ./web
    container_name: gunicorn
    ports:
      - "8001:8001"
    env_file:
      - 'web/secrets.flask'
    networks:
      - backend
    command: bash -c "python manage.py db upgrade && gunicorn --bind=0.0.0.0:8001 --workers=3 manage:app"
    depends_on:
      - influxdb
      - grafana
      - postgres
  
  postgres:
    build: ./postgres
    container_name: postgres
    ports:
      - "5431:5432"
    env_file:
      - 'postgres/secrets.postgres'
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - 'influxdb/env.influxdb'
      - 'influxdb/secrets.influxdb'
    networks:
      - backend
    volumes:
      - influxdb-data:/var/lib/influxdb
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'grafana/env.grafana'
      - 'grafana/secrets.grafana'
    networks:
      - backend
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

networks:
  backend:

volumes:
  influxdb-data:
  grafana-data:
  postgres-data:
